/*
 * Сервис проверки контрагентов с целью ПОД/ФТ
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using ComplianceService.Attributes;
using ComplianceService.Services;
using Microsoft.AspNetCore.Authorization;
using ComplianceService.Models;

namespace ComplianceService.Controllers
{ 
    [ApiController]
    public class CheckDocumentApiController : ControllerBase
    {
        readonly BankCheckService _bankCheckService;
        public CheckDocumentApiController(BankCheckService bankCheckService)
        {
            _bankCheckService = bankCheckService;
        }
        /// <summary>
        /// Проверка клиента через сервис недействительных паспортов
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Информация о проверке</response>
        /// <response code="400">bad input parameter</response>
        [HttpPost]
        [Route("/CheckIdentityCard/")]
        [ValidateModelState]
        [SwaggerOperation("CheckIdentityCard")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<IdentityCardCheckResult>), description: "Информация о проверке")]
        public virtual IActionResult CheckIdentityCard([FromBody]IdentityCard body)
        {
            if (body == null)
                return this.BadRequest();
            var result = _bankCheckService.CheckIdentityCard(body);
            return StatusCode(200, result);
        }
    }
}
